/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { FilAddress, FilAddressInterface } from "../FilAddress";

const _abi = [
  {
    inputs: [],
    name: "CallFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "InsufficientFunds",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidAddress",
    type: "error",
  },
];

const _bytecode =
  "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea2646970667358221220b5eac52d6bc80aac8cc2ff8e72cdb8601c60569abed4da3dc295cdeedb530ea664736f6c63430008110033";

export class FilAddress__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<FilAddress> {
    return super.deploy(overrides || {}) as Promise<FilAddress>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): FilAddress {
    return super.attach(address) as FilAddress;
  }
  connect(signer: Signer): FilAddress__factory {
    return super.connect(signer) as FilAddress__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): FilAddressInterface {
    return new utils.Interface(_abi) as FilAddressInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): FilAddress {
    return new Contract(address, _abi, signerOrProvider) as FilAddress;
  }
}
