/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ISubnetActor, ISubnetActorInterface } from "../ISubnetActor";

const _abi = [
  {
    inputs: [],
    name: "join",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "kill",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "leave",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "reward",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "address[]",
                name: "route",
                type: "address[]",
              },
            ],
            internalType: "struct SubnetID",
            name: "source",
            type: "tuple",
          },
          {
            internalType: "uint64",
            name: "epoch",
            type: "uint64",
          },
          {
            internalType: "uint256",
            name: "fee",
            type: "uint256",
          },
          {
            components: [
              {
                components: [
                  {
                    components: [
                      {
                        components: [
                          {
                            internalType: "address[]",
                            name: "route",
                            type: "address[]",
                          },
                        ],
                        internalType: "struct SubnetID",
                        name: "subnetId",
                        type: "tuple",
                      },
                      {
                        internalType: "address",
                        name: "rawAddress",
                        type: "address",
                      },
                    ],
                    internalType: "struct IPCAddress",
                    name: "from",
                    type: "tuple",
                  },
                  {
                    components: [
                      {
                        components: [
                          {
                            internalType: "address[]",
                            name: "route",
                            type: "address[]",
                          },
                        ],
                        internalType: "struct SubnetID",
                        name: "subnetId",
                        type: "tuple",
                      },
                      {
                        internalType: "address",
                        name: "rawAddress",
                        type: "address",
                      },
                    ],
                    internalType: "struct IPCAddress",
                    name: "to",
                    type: "tuple",
                  },
                  {
                    internalType: "uint256",
                    name: "value",
                    type: "uint256",
                  },
                  {
                    internalType: "uint64",
                    name: "nonce",
                    type: "uint64",
                  },
                  {
                    internalType: "bytes4",
                    name: "method",
                    type: "bytes4",
                  },
                  {
                    internalType: "bytes",
                    name: "params",
                    type: "bytes",
                  },
                ],
                internalType: "struct StorableMsg",
                name: "message",
                type: "tuple",
              },
              {
                internalType: "bool",
                name: "wrapped",
                type: "bool",
              },
            ],
            internalType: "struct CrossMsg[]",
            name: "crossMsgs",
            type: "tuple[]",
          },
          {
            components: [
              {
                components: [
                  {
                    internalType: "address[]",
                    name: "route",
                    type: "address[]",
                  },
                ],
                internalType: "struct SubnetID",
                name: "source",
                type: "tuple",
              },
              {
                internalType: "bytes32[]",
                name: "checks",
                type: "bytes32[]",
              },
            ],
            internalType: "struct ChildCheck[]",
            name: "children",
            type: "tuple[]",
          },
          {
            internalType: "bytes32",
            name: "prevHash",
            type: "bytes32",
          },
        ],
        internalType: "struct BottomUpCheckpoint",
        name: "checkpoint",
        type: "tuple",
      },
    ],
    name: "submitCheckpoint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ISubnetActor__factory {
  static readonly abi = _abi;
  static createInterface(): ISubnetActorInterface {
    return new utils.Interface(_abi) as ISubnetActorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISubnetActor {
    return new Contract(address, _abi, signerOrProvider) as ISubnetActor;
  }
}
