/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface CheckpointHelperInterface extends ethers.utils.Interface {
  functions: {
    "isEmpty((uint64,tuple[]))": FunctionFragment;
    "toHash(((address[]),uint64,uint256,tuple[],tuple[],bytes32))": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "isEmpty",
    values: [
      {
        epoch: BigNumberish;
        topDownMsgs: {
          message: {
            from: { subnetId: { route: string[] }; rawAddress: string };
            to: { subnetId: { route: string[] }; rawAddress: string };
            value: BigNumberish;
            nonce: BigNumberish;
            method: BytesLike;
            params: BytesLike;
          };
          wrapped: boolean;
        }[];
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "toHash",
    values: [
      {
        source: { route: string[] };
        epoch: BigNumberish;
        fee: BigNumberish;
        crossMsgs: {
          message: {
            from: { subnetId: { route: string[] }; rawAddress: string };
            to: { subnetId: { route: string[] }; rawAddress: string };
            value: BigNumberish;
            nonce: BigNumberish;
            method: BytesLike;
            params: BytesLike;
          };
          wrapped: boolean;
        }[];
        children: { source: { route: string[] }; checks: BytesLike[] }[];
        prevHash: BytesLike;
      }
    ]
  ): string;

  decodeFunctionResult(functionFragment: "isEmpty", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "toHash", data: BytesLike): Result;

  events: {};
}

export class CheckpointHelper extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: CheckpointHelperInterface;

  functions: {
    "isEmpty((uint64,tuple[]))"(
      topdownCheckpoint: {
        epoch: BigNumberish;
        topDownMsgs: {
          message: {
            from: { subnetId: { route: string[] }; rawAddress: string };
            to: { subnetId: { route: string[] }; rawAddress: string };
            value: BigNumberish;
            nonce: BigNumberish;
            method: BytesLike;
            params: BytesLike;
          };
          wrapped: boolean;
        }[];
      },
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "isEmpty(((address[]),uint64,uint256,tuple[],tuple[],bytes32))"(
      bottomUpCheckpoint: {
        source: { route: string[] };
        epoch: BigNumberish;
        fee: BigNumberish;
        crossMsgs: {
          message: {
            from: { subnetId: { route: string[] }; rawAddress: string };
            to: { subnetId: { route: string[] }; rawAddress: string };
            value: BigNumberish;
            nonce: BigNumberish;
            method: BytesLike;
            params: BytesLike;
          };
          wrapped: boolean;
        }[];
        children: { source: { route: string[] }; checks: BytesLike[] }[];
        prevHash: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "toHash(((address[]),uint64,uint256,tuple[],tuple[],bytes32))"(
      bottomupCheckpoint: {
        source: { route: string[] };
        epoch: BigNumberish;
        fee: BigNumberish;
        crossMsgs: {
          message: {
            from: { subnetId: { route: string[] }; rawAddress: string };
            to: { subnetId: { route: string[] }; rawAddress: string };
            value: BigNumberish;
            nonce: BigNumberish;
            method: BytesLike;
            params: BytesLike;
          };
          wrapped: boolean;
        }[];
        children: { source: { route: string[] }; checks: BytesLike[] }[];
        prevHash: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<[string]>;

    "toHash((uint64,tuple[]))"(
      topdownCheckpoint: {
        epoch: BigNumberish;
        topDownMsgs: {
          message: {
            from: { subnetId: { route: string[] }; rawAddress: string };
            to: { subnetId: { route: string[] }; rawAddress: string };
            value: BigNumberish;
            nonce: BigNumberish;
            method: BytesLike;
            params: BytesLike;
          };
          wrapped: boolean;
        }[];
      },
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  "isEmpty((uint64,tuple[]))"(
    topdownCheckpoint: {
      epoch: BigNumberish;
      topDownMsgs: {
        message: {
          from: { subnetId: { route: string[] }; rawAddress: string };
          to: { subnetId: { route: string[] }; rawAddress: string };
          value: BigNumberish;
          nonce: BigNumberish;
          method: BytesLike;
          params: BytesLike;
        };
        wrapped: boolean;
      }[];
    },
    overrides?: CallOverrides
  ): Promise<boolean>;

  "isEmpty(((address[]),uint64,uint256,tuple[],tuple[],bytes32))"(
    bottomUpCheckpoint: {
      source: { route: string[] };
      epoch: BigNumberish;
      fee: BigNumberish;
      crossMsgs: {
        message: {
          from: { subnetId: { route: string[] }; rawAddress: string };
          to: { subnetId: { route: string[] }; rawAddress: string };
          value: BigNumberish;
          nonce: BigNumberish;
          method: BytesLike;
          params: BytesLike;
        };
        wrapped: boolean;
      }[];
      children: { source: { route: string[] }; checks: BytesLike[] }[];
      prevHash: BytesLike;
    },
    overrides?: CallOverrides
  ): Promise<boolean>;

  "toHash(((address[]),uint64,uint256,tuple[],tuple[],bytes32))"(
    bottomupCheckpoint: {
      source: { route: string[] };
      epoch: BigNumberish;
      fee: BigNumberish;
      crossMsgs: {
        message: {
          from: { subnetId: { route: string[] }; rawAddress: string };
          to: { subnetId: { route: string[] }; rawAddress: string };
          value: BigNumberish;
          nonce: BigNumberish;
          method: BytesLike;
          params: BytesLike;
        };
        wrapped: boolean;
      }[];
      children: { source: { route: string[] }; checks: BytesLike[] }[];
      prevHash: BytesLike;
    },
    overrides?: CallOverrides
  ): Promise<string>;

  "toHash((uint64,tuple[]))"(
    topdownCheckpoint: {
      epoch: BigNumberish;
      topDownMsgs: {
        message: {
          from: { subnetId: { route: string[] }; rawAddress: string };
          to: { subnetId: { route: string[] }; rawAddress: string };
          value: BigNumberish;
          nonce: BigNumberish;
          method: BytesLike;
          params: BytesLike;
        };
        wrapped: boolean;
      }[];
    },
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    "isEmpty((uint64,tuple[]))"(
      topdownCheckpoint: {
        epoch: BigNumberish;
        topDownMsgs: {
          message: {
            from: { subnetId: { route: string[] }; rawAddress: string };
            to: { subnetId: { route: string[] }; rawAddress: string };
            value: BigNumberish;
            nonce: BigNumberish;
            method: BytesLike;
            params: BytesLike;
          };
          wrapped: boolean;
        }[];
      },
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isEmpty(((address[]),uint64,uint256,tuple[],tuple[],bytes32))"(
      bottomUpCheckpoint: {
        source: { route: string[] };
        epoch: BigNumberish;
        fee: BigNumberish;
        crossMsgs: {
          message: {
            from: { subnetId: { route: string[] }; rawAddress: string };
            to: { subnetId: { route: string[] }; rawAddress: string };
            value: BigNumberish;
            nonce: BigNumberish;
            method: BytesLike;
            params: BytesLike;
          };
          wrapped: boolean;
        }[];
        children: { source: { route: string[] }; checks: BytesLike[] }[];
        prevHash: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<boolean>;

    "toHash(((address[]),uint64,uint256,tuple[],tuple[],bytes32))"(
      bottomupCheckpoint: {
        source: { route: string[] };
        epoch: BigNumberish;
        fee: BigNumberish;
        crossMsgs: {
          message: {
            from: { subnetId: { route: string[] }; rawAddress: string };
            to: { subnetId: { route: string[] }; rawAddress: string };
            value: BigNumberish;
            nonce: BigNumberish;
            method: BytesLike;
            params: BytesLike;
          };
          wrapped: boolean;
        }[];
        children: { source: { route: string[] }; checks: BytesLike[] }[];
        prevHash: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<string>;

    "toHash((uint64,tuple[]))"(
      topdownCheckpoint: {
        epoch: BigNumberish;
        topDownMsgs: {
          message: {
            from: { subnetId: { route: string[] }; rawAddress: string };
            to: { subnetId: { route: string[] }; rawAddress: string };
            value: BigNumberish;
            nonce: BigNumberish;
            method: BytesLike;
            params: BytesLike;
          };
          wrapped: boolean;
        }[];
      },
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    "isEmpty((uint64,tuple[]))"(
      topdownCheckpoint: {
        epoch: BigNumberish;
        topDownMsgs: {
          message: {
            from: { subnetId: { route: string[] }; rawAddress: string };
            to: { subnetId: { route: string[] }; rawAddress: string };
            value: BigNumberish;
            nonce: BigNumberish;
            method: BytesLike;
            params: BytesLike;
          };
          wrapped: boolean;
        }[];
      },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isEmpty(((address[]),uint64,uint256,tuple[],tuple[],bytes32))"(
      bottomUpCheckpoint: {
        source: { route: string[] };
        epoch: BigNumberish;
        fee: BigNumberish;
        crossMsgs: {
          message: {
            from: { subnetId: { route: string[] }; rawAddress: string };
            to: { subnetId: { route: string[] }; rawAddress: string };
            value: BigNumberish;
            nonce: BigNumberish;
            method: BytesLike;
            params: BytesLike;
          };
          wrapped: boolean;
        }[];
        children: { source: { route: string[] }; checks: BytesLike[] }[];
        prevHash: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "toHash(((address[]),uint64,uint256,tuple[],tuple[],bytes32))"(
      bottomupCheckpoint: {
        source: { route: string[] };
        epoch: BigNumberish;
        fee: BigNumberish;
        crossMsgs: {
          message: {
            from: { subnetId: { route: string[] }; rawAddress: string };
            to: { subnetId: { route: string[] }; rawAddress: string };
            value: BigNumberish;
            nonce: BigNumberish;
            method: BytesLike;
            params: BytesLike;
          };
          wrapped: boolean;
        }[];
        children: { source: { route: string[] }; checks: BytesLike[] }[];
        prevHash: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "toHash((uint64,tuple[]))"(
      topdownCheckpoint: {
        epoch: BigNumberish;
        topDownMsgs: {
          message: {
            from: { subnetId: { route: string[] }; rawAddress: string };
            to: { subnetId: { route: string[] }; rawAddress: string };
            value: BigNumberish;
            nonce: BigNumberish;
            method: BytesLike;
            params: BytesLike;
          };
          wrapped: boolean;
        }[];
      },
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    "isEmpty((uint64,tuple[]))"(
      topdownCheckpoint: {
        epoch: BigNumberish;
        topDownMsgs: {
          message: {
            from: { subnetId: { route: string[] }; rawAddress: string };
            to: { subnetId: { route: string[] }; rawAddress: string };
            value: BigNumberish;
            nonce: BigNumberish;
            method: BytesLike;
            params: BytesLike;
          };
          wrapped: boolean;
        }[];
      },
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isEmpty(((address[]),uint64,uint256,tuple[],tuple[],bytes32))"(
      bottomUpCheckpoint: {
        source: { route: string[] };
        epoch: BigNumberish;
        fee: BigNumberish;
        crossMsgs: {
          message: {
            from: { subnetId: { route: string[] }; rawAddress: string };
            to: { subnetId: { route: string[] }; rawAddress: string };
            value: BigNumberish;
            nonce: BigNumberish;
            method: BytesLike;
            params: BytesLike;
          };
          wrapped: boolean;
        }[];
        children: { source: { route: string[] }; checks: BytesLike[] }[];
        prevHash: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "toHash(((address[]),uint64,uint256,tuple[],tuple[],bytes32))"(
      bottomupCheckpoint: {
        source: { route: string[] };
        epoch: BigNumberish;
        fee: BigNumberish;
        crossMsgs: {
          message: {
            from: { subnetId: { route: string[] }; rawAddress: string };
            to: { subnetId: { route: string[] }; rawAddress: string };
            value: BigNumberish;
            nonce: BigNumberish;
            method: BytesLike;
            params: BytesLike;
          };
          wrapped: boolean;
        }[];
        children: { source: { route: string[] }; checks: BytesLike[] }[];
        prevHash: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "toHash((uint64,tuple[]))"(
      topdownCheckpoint: {
        epoch: BigNumberish;
        topDownMsgs: {
          message: {
            from: { subnetId: { route: string[] }; rawAddress: string };
            to: { subnetId: { route: string[] }; rawAddress: string };
            value: BigNumberish;
            nonce: BigNumberish;
            method: BytesLike;
            params: BytesLike;
          };
          wrapped: boolean;
        }[];
      },
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
