/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface VotingInterface extends ethers.utils.Interface {
  functions: {
    "executableQueue()": FunctionFragment;
    "genesisEpoch()": FunctionFragment;
    "lastVotingExecutedEpoch()": FunctionFragment;
    "majorityPercentage()": FunctionFragment;
    "submissionPeriod()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "executableQueue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "genesisEpoch",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastVotingExecutedEpoch",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "majorityPercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submissionPeriod",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "executableQueue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "genesisEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastVotingExecutedEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "majorityPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submissionPeriod",
    data: BytesLike
  ): Result;

  events: {};
}

export class Voting extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: VotingInterface;

  functions: {
    executableQueue(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        period: BigNumber;
        first: BigNumber;
        last: BigNumber;
      }
    >;

    genesisEpoch(overrides?: CallOverrides): Promise<[BigNumber]>;

    lastVotingExecutedEpoch(overrides?: CallOverrides): Promise<[BigNumber]>;

    majorityPercentage(overrides?: CallOverrides): Promise<[number]>;

    submissionPeriod(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  executableQueue(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      period: BigNumber;
      first: BigNumber;
      last: BigNumber;
    }
  >;

  genesisEpoch(overrides?: CallOverrides): Promise<BigNumber>;

  lastVotingExecutedEpoch(overrides?: CallOverrides): Promise<BigNumber>;

  majorityPercentage(overrides?: CallOverrides): Promise<number>;

  submissionPeriod(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    executableQueue(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        period: BigNumber;
        first: BigNumber;
        last: BigNumber;
      }
    >;

    genesisEpoch(overrides?: CallOverrides): Promise<BigNumber>;

    lastVotingExecutedEpoch(overrides?: CallOverrides): Promise<BigNumber>;

    majorityPercentage(overrides?: CallOverrides): Promise<number>;

    submissionPeriod(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    executableQueue(overrides?: CallOverrides): Promise<BigNumber>;

    genesisEpoch(overrides?: CallOverrides): Promise<BigNumber>;

    lastVotingExecutedEpoch(overrides?: CallOverrides): Promise<BigNumber>;

    majorityPercentage(overrides?: CallOverrides): Promise<BigNumber>;

    submissionPeriod(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    executableQueue(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    genesisEpoch(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lastVotingExecutedEpoch(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    majorityPercentage(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    submissionPeriod(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
